#!/usr/bin/env python3
"""
Backfill SEO engagement (reactions + comments) wrapper across every consumer site.

Reads config.json, finds every `projects[].landing_pages.repo`, and:

1. Writes `<app_dir>/seo-engagement.tsx` with a pathname-allowlist wrapper
   that renders `<SeoPageReactions>` + `<SeoPageComments>` only on SEO
   routes (/t/, /alternative/, /use-case/, /best/, /blog/, /guides/).
2. Injects `<SeoEngagement />` into the root `<app_dir>/layout.tsx`
   right after the first `{children}` reference (so it sits inside the
   site's main column), plus the matching `import { SeoEngagement } from
   "./seo-engagement";` near the top.
3. Cleans up legacy per-route copies: if a site previously had
   `<app_dir>/<route>/seo-engagement.tsx` + a render line inside
   `<app_dir>/<route>/layout.tsx`, those are removed to avoid duplicate
   reactions/comments. Layouts that exist solely for the engagement wrapper
   (i.e. only `{children}` + `<SeoEngagement />` left after stripping) are
   deleted entirely.

Idempotent: re-running on an already-fixed site is a no-op.

Usage:
    python3 scripts/backfill_seo_engagement.py [--dry-run] [--only <name>,<name>]
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "config.json"

# Route prefixes the SEO pipeline writes to. Mirror of CONTENT_TYPES in
# seo/generate_page.py plus mediar's legacy `/guides/` alias.
SEO_PREFIXES = ["/t/", "/alternative/", "/use-case/", "/best/", "/blog/", "/guides/"]


def expand(p: str) -> Path:
    return Path(os.path.expanduser(p)).resolve()


def detect_app_dir(repo: Path) -> Path | None:
    for cand in ("src/app", "app"):
        if (repo / cand / "layout.tsx").exists():
            return repo / cand
    return None


def domain_from_website(url: str) -> str:
    """https://www.fazm.ai -> fazm.ai (strip scheme, leading www., trailing /)."""
    u = (url or "").strip()
    u = re.sub(r"^https?://", "", u)
    u = re.sub(r"^www\.", "", u)
    u = u.rstrip("/")
    return u


def engagement_component(domain: str) -> str:
    prefix_array = ", ".join(f'"{p}"' for p in SEO_PREFIXES)
    return f'''"use client";

// AUTO-GENERATED by scripts/backfill_seo_engagement.py.
// Renders <SeoPageReactions> and <SeoPageComments> from @m13v/seo-components
// at the bottom of every SEO page (route prefixes below). Returns null on
// non-SEO routes so the homepage / pricing / etc. stay clean.

import {{ usePathname }} from "next/navigation";
import {{ SeoPageComments, SeoPageReactions }} from "@seo/components";

const API = process.env.NEXT_PUBLIC_AUTOPOSTER_API || "https://s4l.ai";
const SITE = "{domain}";
const SEO_PREFIXES: string[] = [{prefix_array}];

export function SeoEngagement() {{
  const pathname = usePathname() || "";
  const onSeoRoute = SEO_PREFIXES.some((p) => pathname.startsWith(p));
  if (!onSeoRoute) return null;
  return (
    <>
      <SeoPageReactions site={{SITE}} pageSlug={{pathname}} apiOrigin={{API}} />
      <SeoPageComments site={{SITE}} pageSlug={{pathname}} apiOrigin={{API}} />
    </>
  );
}}
'''


# --- root layout patching ---------------------------------------------------

IMPORT_LINE = 'import { SeoEngagement } from "./seo-engagement";'
RENDER_TAG = "<SeoEngagement />"


def patch_root_layout(layout_path: Path) -> tuple[bool, str]:
    """Add the import + render to a site's root layout.tsx. Returns
    (changed, status_message)."""
    src = layout_path.read_text()
    if RENDER_TAG in src and IMPORT_LINE in src:
        return False, "already wired"

    new = src

    # Add import line if missing. Drop it after the last existing top-level
    # import so it sits with the rest of the imports.
    if IMPORT_LINE not in new:
        import_matches = list(re.finditer(r'(?m)^import [^;]+;\n', new))
        if import_matches:
            last = import_matches[-1]
            insert_at = last.end()
            new = new[:insert_at] + IMPORT_LINE + "\n" + new[insert_at:]
        else:
            new = IMPORT_LINE + "\n" + new

    # Inject the render right after the FIRST `{children}` occurrence (which
    # is always the main slot). We avoid touching subsequent ones (e.g. modal
    # slots) by only replacing the first match.
    if RENDER_TAG not in new:
        m = re.search(r"\{children\}", new)
        if not m:
            return False, "no {children} found, manual patch needed"
        insert_at = m.end()
        # Compute the leading whitespace of the line containing {children}
        line_start = new.rfind("\n", 0, m.start()) + 1
        indent = ""
        for ch in new[line_start : m.start()]:
            if ch in (" ", "\t"):
                indent += ch
            else:
                break
        new = new[:insert_at] + f"\n{indent}{RENDER_TAG}" + new[insert_at:]

    if new == src:
        return False, "no change"

    layout_path.write_text(new)
    return True, "patched"


# --- legacy per-route cleanup ----------------------------------------------

def strip_legacy_per_route(app_dir: Path) -> list[str]:
    """Find existing per-route `seo-engagement.tsx` siblings and remove the
    duplicate wiring. Returns a list of status messages."""
    msgs: list[str] = []
    for legacy_eng in app_dir.rglob("seo-engagement.tsx"):
        if legacy_eng.parent == app_dir:
            # This is the canonical root one we just wrote; skip.
            continue
        route_layout = legacy_eng.with_name("layout.tsx")
        # Always delete the per-route seo-engagement.tsx
        legacy_eng.unlink()
        msgs.append(f"removed {legacy_eng.relative_to(app_dir)}")

        if route_layout.exists():
            txt = route_layout.read_text()
            new_txt = txt
            # Remove import line(s) pointing at the local ./seo-engagement
            new_txt = re.sub(
                r'(?m)^import \{ SeoEngagement \} from "\./seo-engagement";\n',
                "",
                new_txt,
            )
            # Remove the render line, allowing surrounding whitespace
            new_txt = re.sub(
                r'(?m)^[ \t]*<SeoEngagement\s*/>\s*\n',
                "",
                new_txt,
            )

            # If after stripping the layout collapses to just `<>{children}</>`
            # (i.e. it existed only for the wrapper), delete the file.
            useless = re.compile(
                r'export default function \w+\(\{ ?children ?\}: ?\{ ?children: React\.ReactNode ?\}\) ?\{\s*return \(\s*<>\s*\{children\}\s*</>\s*\);\s*\}',
                re.DOTALL,
            )
            stripped_for_check = re.sub(r"\s+", "", new_txt)
            collapsed = (
                "exportdefaultfunction" in stripped_for_check
                and "<>{children}</>" in stripped_for_check
                and len(stripped_for_check) < 250  # heuristic: tiny layout
                and "SiteNavbar" not in new_txt
                and "SiteFooter" not in new_txt
                and "SeoNavbar" not in new_txt
            )
            if collapsed:
                route_layout.unlink()
                msgs.append(f"deleted now-empty {route_layout.relative_to(app_dir)}")
            elif new_txt != txt:
                route_layout.write_text(new_txt)
                msgs.append(f"stripped wrapper from {route_layout.relative_to(app_dir)}")
    return msgs


# --- top-level driver ------------------------------------------------------

def process_project(project: dict, dry_run: bool) -> dict:
    name = project.get("name", "?")
    website = project.get("website") or ""
    lp = project.get("landing_pages") or {}
    repo_str = lp.get("repo")
    if not repo_str:
        return {"name": name, "status": "skip", "reason": "no landing_pages.repo"}

    repo = expand(repo_str)
    if not repo.exists():
        return {"name": name, "status": "skip", "reason": f"repo {repo} missing"}

    app_dir = detect_app_dir(repo)
    if not app_dir:
        return {"name": name, "status": "skip", "reason": "no app/layout.tsx or src/app/layout.tsx"}

    domain = domain_from_website(website)
    if not domain:
        return {"name": name, "status": "skip", "reason": "no website in config"}

    actions: list[str] = []
    eng_path = app_dir / "seo-engagement.tsx"
    desired = engagement_component(domain)

    # Step 1: write engagement component if missing or stale.
    existing = eng_path.read_text() if eng_path.exists() else None
    if existing != desired:
        if dry_run:
            actions.append(f"would write {eng_path.relative_to(repo)}")
        else:
            eng_path.write_text(desired)
            actions.append(f"wrote {eng_path.relative_to(repo)}")

    # Step 2: patch root layout.
    layout = app_dir / "layout.tsx"
    if dry_run:
        # Inspect-only: report whether patching would do anything.
        src = layout.read_text()
        if RENDER_TAG in src and IMPORT_LINE in src:
            actions.append(f"{layout.relative_to(repo)}: already wired")
        else:
            actions.append(f"would patch {layout.relative_to(repo)}")
    else:
        changed, msg = patch_root_layout(layout)
        if changed:
            actions.append(f"patched {layout.relative_to(repo)} ({msg})")
        elif "already wired" in msg:
            actions.append(f"{layout.relative_to(repo)}: already wired")
        elif "no {children}" in msg:
            actions.append(f"WARN {layout.relative_to(repo)}: {msg}")
        else:
            actions.append(f"{layout.relative_to(repo)}: {msg}")

    # Step 3: clean up legacy per-route wrappers.
    if dry_run:
        for legacy in app_dir.rglob("seo-engagement.tsx"):
            if legacy.parent != app_dir:
                actions.append(f"would remove legacy {legacy.relative_to(repo)}")
    else:
        actions.extend(strip_legacy_per_route(app_dir))

    return {"name": name, "status": "ok", "app_dir": str(app_dir.relative_to(repo)), "domain": domain, "actions": actions}


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="report planned changes; do not write")
    parser.add_argument("--only", help="comma-separated project name filter (matches config.json `name`)")
    args = parser.parse_args(argv)

    config = json.loads(CONFIG_PATH.read_text())
    projects = config.get("projects", [])

    only = {s.strip() for s in args.only.split(",")} if args.only else None

    results: list[dict] = []
    for p in projects:
        if only and p.get("name") not in only:
            continue
        results.append(process_project(p, dry_run=args.dry_run))

    # Pretty report
    print(f"Mode: {'DRY-RUN' if args.dry_run else 'APPLY'}")
    print(f"Processed: {len(results)} project(s)\n")
    for r in results:
        if r["status"] == "skip":
            print(f"  - {r['name']}: SKIP ({r['reason']})")
            continue
        print(f"  + {r['name']} [{r['app_dir']} -> {r['domain']}]")
        for a in r["actions"]:
            print(f"      {a}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
