#!/usr/bin/env python3
"""Turn a scan_x_profile.py corpus into durable author-voice exemplars.

WHERE THIS FITS: scan_x_profile.py (run at onboarding right after connect_x,
or later via build_persona.py gather) returns the user's real posts + replies
ranked by engagement (`top_posts` / `top_replies`, each with likes/retweets/
replies, the parent tweet replied to, and thread continuations). This script is
the single deterministic writer that persists them where the drafters already
look:

  1. config.json -> project.voice.examples (list of strings). Every drafting
     prompt already says "mirror voice.examples / voice.examples_good when
     present": the twitter cycle (both promotion and personal_brand lanes, via
     ALL_PROJECTS_JSON), post_reddit.py, engage_reddit.py, post_github.py, and
     run_moltbook_cycle.py. Writing this ONE field feeds every lane on every
     platform with zero prompt changes.
  2. persona_corpus.txt (persona project only) -> a marked, regenerable
     exemplar section with the top posts (incl. thread continuations) and top
     replies WITH their parent context and stats. The personal_brand lane
     inlines this file into the draft prompt.

Selection: prefers replies with real engagement and enough text to show voice
(skips throwaway one-liners below --min-chars unless nothing else exists).
Stats are framed RELATIVELY ("top of the N scanned replies") because absolute
numbers on small accounts mean nothing to the model.

Safety: never clobbers hand-written voice.examples. It only replaces examples
it wrote itself (voice.examples_scanned_at present) or fills an empty field;
use --force to override. Config writes are atomic (tmp + replace), matching
build_persona.py.

Usage:
  # After a scan (writes voice.examples; also corpus section if project is the persona):
  python3 scripts/scan_x_profile.py > /tmp/scan.json
  python3 scripts/voice_exemplars.py apply --scan /tmp/scan.json --project MyProject

  # Preview without writing:
  python3 scripts/voice_exemplars.py apply --scan /tmp/scan.json --project MyProject --dry-run

  # Default project = the persona project (persona:true) when --project omitted.

Accepts either raw scan_x_profile.py output or a build_persona.py gather blob
(auto-detects sources.x).
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import s4l_mode  # noqa: E402

EXEMPLARS_START = "=== S4L SCANNED EXEMPLARS START (auto-generated by voice_exemplars.py; regenerated on rescan, do not hand-edit) ==="
EXEMPLARS_END = "=== S4L SCANNED EXEMPLARS END ==="


def _score(item: dict) -> int:
    """Mirror scan_x_profile.rank_top's weighting for scans that predate it."""
    if "engagement_score" in item:
        return int(item["engagement_score"] or 0)
    return (int(item.get("likes") or 0) * 3
            + int(item.get("retweets") or 0) * 5
            + int(item.get("replies") or 0) * 2)


def _load_scan(path: str) -> dict:
    data = json.loads(Path(path).expanduser().read_text())
    # build_persona.py gather embeds the raw scan under sources.x
    if "sources" in data and isinstance(data["sources"], dict):
        x = data["sources"].get("x") or {}
        if x.get("ok"):
            return x
        raise SystemExit(f"gather blob's x source is not ok: {x.get('error')}")
    return data


def _pick(items: list, top: int, min_chars: int) -> list:
    """Engagement-ranked, but a reply must have enough text to show voice.
    Short high-engagement one-liners get skipped while longer candidates exist;
    if the account only has one-liners, fall back rather than return nothing."""
    ranked = sorted(items or [], key=_score, reverse=True)
    long_enough = [i for i in ranked if len((i.get("text") or "").strip()) >= min_chars]
    picked = long_enough[:top]
    if not picked:
        picked = ranked[:top]
    return picked


def _reply_pool(scan: dict) -> list:
    """Select from the FULL scanned reply list, not the scanner's pre-truncated
    top_replies (length-filtering a 5-item list can leave one survivor when the
    account's best-engaging replies are one-liners). top_replies is the
    fallback for older scans / gather blobs that dropped the full list."""
    return scan.get("comments") or scan.get("top_replies") or []


def _post_pool(scan: dict) -> list:
    """Full post list, but prefer the enriched top_posts entry where one exists
    (it carries the thread continuation and untruncated permalink text)."""
    top = scan.get("top_posts") or []
    rest = scan.get("posts") or []
    by_key = {(p.get("id") or p.get("url") or p.get("text", "")[:80]): p for p in rest}
    for p in top:
        by_key[(p.get("id") or p.get("url") or p.get("text", "")[:80])] = p
    return list(by_key.values())


def _stats_note(item: dict, total: int, kind: str) -> str:
    bits = []
    for key, label in (("likes", "likes"), ("retweets", "reposts"), ("replies", "replies")):
        v = int(item.get(key) or 0)
        if v:
            bits.append(f"{v} {label}")
    eng = ", ".join(bits) if bits else "no engagement yet"
    return f"{eng}; among their best of {total} scanned {kind}"


def format_examples(scan: dict, top: int, min_chars: int) -> list[str]:
    """voice.examples strings: verbatim reply first (the voice signal), then a
    parenthesized context annotation (real stats + what it replied to). Plain
    strings because every consumer joins/inlines them as-is."""
    replies = _reply_pool(scan)
    total = int((scan.get("counts") or {}).get("comments") or len(replies))
    out = []
    for r in _pick(replies, top, min_chars):
        text = (r.get("text") or "").strip()
        if not text:
            continue
        note = _stats_note(r, total, "replies")
        parent = r.get("parent") or {}
        if parent.get("text"):
            ptxt = " ".join(parent["text"].split())[:140]
            note += f'; replying to {parent.get("author") or "someone"}: "{ptxt}"'
        out.append(f'"{text}" (their real reply, {note})')
    return out


def format_corpus_section(scan: dict, top: int, min_chars: int) -> str:
    """The persona_corpus.txt block: richer than voice.examples (adds top posts
    and full thread continuations). Regenerated wholesale between the markers."""
    handle = scan.get("handle") or "?"
    counts = scan.get("counts") or {}
    lines = [EXEMPLARS_START,
             f"@{handle}'s own top-performing posts and replies, ranked by real "
             f"engagement across {counts.get('posts', '?')} posts and "
             f"{counts.get('comments', '?')} replies scanned. Verbatim. This is "
             "the voice and the bar: ground drafts in this register.", ""]
    posts = _pick(_post_pool(scan), top, min_chars)
    if posts:
        lines.append("TOP POSTS:")
        for p in posts:
            lines.append(f"- ({_stats_note(p, int(counts.get('posts') or len(posts)), 'posts')}) {p.get('text', '').strip()}")
            for cont in (p.get("thread") or [])[1:]:
                lines.append(f"  [thread continuation] {cont.strip()}")
        lines.append("")
    replies = _pick(_reply_pool(scan), top, min_chars)
    if replies:
        lines.append("TOP REPLIES (with what they replied to):")
        for r in replies:
            parent = r.get("parent") or {}
            if parent.get("text"):
                ptxt = " ".join(parent["text"].split())[:200]
                lines.append(f'- {parent.get("author") or "someone"} wrote: "{ptxt}"')
                lines.append(f"  their reply ({_stats_note(r, int(counts.get('comments') or len(replies)), 'replies')}): {r.get('text', '').strip()}")
            else:
                lines.append(f"- their reply ({_stats_note(r, int(counts.get('comments') or len(replies)), 'replies')}): {r.get('text', '').strip()}")
    lines.append(EXEMPLARS_END)
    return "\n".join(lines)


def _upsert_corpus_section(corpus_path: Path, section: str) -> str:
    """Replace the marked section in persona_corpus.txt, or prepend it (top of
    file for salience) when absent. Returns what happened."""
    if corpus_path.exists():
        body = corpus_path.read_text()
        if EXEMPLARS_START in body and EXEMPLARS_END in body:
            pre = body.split(EXEMPLARS_START)[0]
            post = body.split(EXEMPLARS_END, 1)[1]
            corpus_path.write_text((pre + section + post).strip() + "\n")
            return "replaced"
        corpus_path.write_text(section + "\n\n" + body.strip() + "\n")
        return "prepended"
    corpus_path.write_text(section + "\n")
    return "created"


def cmd_apply(args) -> int:
    cfg_path = Path(args.config).expanduser() if args.config else s4l_mode.config_path()
    scan_src = args.scan or str(cfg_path.parent / "last_profile_scan.json")
    if not Path(scan_src).expanduser().exists():
        print(json.dumps({"ok": False, "error": f"no scan at {scan_src}; run "
                          "scan_x_profile.py first (it writes last_profile_scan.json) "
                          "or pass --scan"}))
        return 1
    scan = _load_scan(scan_src)
    if not scan.get("ok"):
        print(json.dumps({"ok": False, "error": f"scan not ok: {scan.get('error')}"}))
        return 1

    cfg = json.loads(cfg_path.read_text())
    projects = cfg.get("projects", [])
    name = args.project or s4l_mode.persona_name()
    proj = next((p for p in projects if p.get("name") == name), None)
    if proj is None:
        print(json.dumps({"ok": False, "error": f"project {name!r} not in {cfg_path} "
                          "(pass --project, or configure a persona project)"}))
        return 2

    examples = format_examples(scan, args.top, args.min_chars)
    if not examples:
        print(json.dumps({"ok": False, "error": "scan has no usable replies to build examples from"}))
        return 1

    voice = proj.get("voice")
    if not isinstance(voice, dict):
        voice = {"tone": voice} if voice else {}
        proj["voice"] = voice
    hand_written = bool(voice.get("examples")) and not voice.get("examples_scanned_at")
    if hand_written and not args.force:
        print(json.dumps({"ok": False, "error":
                          f"{name}.voice.examples already has hand-written entries; "
                          "rerun with --force to replace them",
                          "existing": voice.get("examples")}))
        return 3

    voice["examples"] = examples
    voice["examples_scanned_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")

    is_persona = proj.get("persona") is True
    corpus_path = cfg_path.parent / "persona_corpus.txt"
    section = format_corpus_section(scan, args.top, args.min_chars) if is_persona else None

    if args.dry_run:
        print(json.dumps({"ok": True, "dry_run": True, "project": name,
                          "voice_examples": examples,
                          "corpus_section": section}, ensure_ascii=False, indent=2))
        return 0

    tmp = cfg_path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(cfg, ensure_ascii=False, indent=2) + "\n")
    tmp.replace(cfg_path)

    corpus_action = None
    if section:
        corpus_action = _upsert_corpus_section(corpus_path, section)

    print(json.dumps({"ok": True, "project": name,
                      "voice_examples_written": len(examples),
                      "corpus_sidecar": str(corpus_path) if corpus_action else None,
                      "corpus_action": corpus_action}, ensure_ascii=False))
    return 0


def main(argv) -> int:
    ap = argparse.ArgumentParser(description="Persist scanned top posts/replies as author-voice exemplars")
    sub = ap.add_subparsers(dest="cmd", required=True)
    a = sub.add_parser("apply", help="write voice.examples (+ persona corpus section)")
    a.add_argument("--scan", default=None,
                   help="scan_x_profile.py JSON or build_persona gather blob "
                        "(default: <config dir>/last_profile_scan.json, written by the scanner)")
    a.add_argument("--project", default=None, help="config.json project name (default: the persona project)")
    a.add_argument("--config", default=None, help="config.json path override (testing)")
    a.add_argument("--top", type=int, default=5, help="max exemplars per surface")
    a.add_argument("--min-chars", type=int, default=40,
                   help="skip replies shorter than this when longer ones exist")
    a.add_argument("--force", action="store_true", help="replace hand-written voice.examples")
    a.add_argument("--dry-run", action="store_true", help="print what would be written")
    a.set_defaults(func=cmd_apply)
    args = ap.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
