-- web_chat_schema.sql
-- Neon Postgres migration for web-based founder chat (mirror of Fazm Firestore schema)
-- Run once: psql "$DATABASE_URL" -f scripts/web_chat_schema.sql
--
-- Two tables:
--   web_chat_threads   parent doc, one per visitor per project
--   web_chat_messages  individual messages in a thread
--
-- Mirrors Fazm's founder_chats / messages layout exactly: unread_by_founder,
-- unread_by_visitor, claimed_until cooldown, last_message_* denormalisation.
-- The pipeline scripts read/write the same column names.

CREATE TABLE IF NOT EXISTS web_chat_threads (
    id SERIAL PRIMARY KEY,
    thread_id TEXT UNIQUE NOT NULL,         -- "wc_<nanoid>" generated by widget on first send
    project_name TEXT NOT NULL,             -- joins config.json projects[].name (case-sensitive)
    visitor_id TEXT NOT NULL,               -- "web_<nanoid>" stored in localStorage on the visitor's browser
    visitor_email TEXT,                     -- captured on first message (may start NULL, becomes required after 1st reply)
    visitor_name TEXT,
    page_url TEXT,                          -- where they were when they sent the first message
    user_agent TEXT,
    referrer TEXT,
    -- Mirror of Firestore semantics:
    unread_by_founder INTEGER NOT NULL DEFAULT 0,
    unread_by_visitor INTEGER NOT NULL DEFAULT 0,
    last_message_sender TEXT,               -- 'visitor' | 'agent' | 'founder'
    last_message_text TEXT,
    last_message_at TIMESTAMPTZ,
    -- Claim/cooldown (prevents duplicate Claude spawns when visitor sends rapid msgs):
    claimed_until TIMESTAMPTZ,
    -- Failure / rate-limit bookkeeping (mirror /tmp/fazm-chat-* files in DB so visible in dashboard):
    fail_count INTEGER NOT NULL DEFAULT 0,
    rate_limited_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wct_unread
    ON web_chat_threads(project_name, unread_by_founder)
    WHERE unread_by_founder > 0;

CREATE INDEX IF NOT EXISTS idx_wct_project_recent
    ON web_chat_threads(project_name, last_message_at DESC);

CREATE INDEX IF NOT EXISTS idx_wct_visitor
    ON web_chat_threads(visitor_id);


CREATE TABLE IF NOT EXISTS web_chat_messages (
    id SERIAL PRIMARY KEY,
    thread_id TEXT NOT NULL REFERENCES web_chat_threads(thread_id) ON DELETE CASCADE,
    sender TEXT NOT NULL,                   -- 'visitor' | 'agent' | 'founder'
    sender_name TEXT,                       -- e.g. "matt", visitor's email, etc.
    text TEXT NOT NULL,
    read_by_founder BOOLEAN NOT NULL DEFAULT FALSE,
    read_by_visitor BOOLEAN NOT NULL DEFAULT FALSE,
    -- For traceability when notification email or Resend reply was dispatched:
    notification_email_id TEXT,             -- Resend id of the [WEB-CHAT #N] email to founder
    visitor_email_id TEXT,                  -- Resend id of the email forwarded to visitor
    -- For the override-via-Gmail rail (mirror ingest_human_dm_replies.py):
    ingested_gmail_id TEXT,                 -- if this message was ingested from a Gmail reply, the message id
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wcm_thread
    ON web_chat_messages(thread_id, created_at);

CREATE INDEX IF NOT EXISTS idx_wcm_sender
    ON web_chat_messages(thread_id, sender, created_at);

-- Partial unique index to prevent re-ingest of the same Gmail reply twice
-- (mirror of human_dm_replies.resend_email_id pattern).
CREATE UNIQUE INDEX IF NOT EXISTS idx_wcm_ingested_gmail_id
    ON web_chat_messages(ingested_gmail_id)
    WHERE ingested_gmail_id IS NOT NULL;


-- Trigger to auto-bump updated_at on every row update.
CREATE OR REPLACE FUNCTION wct_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_wct_touch_updated ON web_chat_threads;
CREATE TRIGGER trg_wct_touch_updated
    BEFORE UPDATE ON web_chat_threads
    FOR EACH ROW EXECUTE FUNCTION wct_touch_updated_at();
